### ISSUE TITLE
Should not limit #connections by IP

### ISSUE THREAD

**Issue by daurnimator** [networkprotocol/netcode.io#1]
> Additionally, the server enforces that only one client with a given IP address may be connected at any time

Not everyone has an IP to themselves. [Carrier grade NATs](https://en.wikipedia.org/wiki/Carrier-grade_NAT) are a thing. In particular you have whole countries behind just a couple of IPs.

**Comment by gafferongames** [comment]
Updated article to reflect what the code actually does:

"Additionally, the server enforces that only one client with a given *IP address and port* may be connected at any time."

My bad.
