### ISSUE TITLE
Verify Endianness of connect token ipv6 addresses

### ISSUE THREAD

**Issue by wirepair** [networkprotocol/netcode.io#17]
While porting the connect token to Go I noticed that I was unable to get the connect token to verify due to a failure in comparing the ipv6 addresses. Attached is a screen shot of the netcode_address_equal while debugging the connect token verification. You'll notice that it appears the final uint16 of an ipv6 address of "::1" looks like it is in big endian.

![ipv6_endian](https://cloud.githubusercontent.com/assets/1073742/24842030/11e54b22-1dcc-11e7-97c8-51ec8f907fd3.png)

I could only get client to server communications working from Go to C by forcing ipv6 to be BigEndian encoded: [code](https://github.com/wirepair/netcode.io/blob/master/go/netcode/connect_token_shared.go#L109)

I'll admit it's been a while since I've done any endianness encoding so my assumptions may be incorrect.

**Comment by gafferongames** [comment]
What does the ipv6 address data look like as an array of bytes in the connect token?

**Comment by gafferongames** [comment]
I would expect the array of bytes should look like:

0x00000000000000000000000000000100

Which when converted from little endian and read into a uint16_t should look like:

0x0001 in the uint16 value?

**Comment by gafferongames** [comment]
(because little endian switches byte order from a uint16 when its read in from memory, while big endian does not... but for both little endian and big endian, the format of a uint16_t in register is the same).

**Comment by wirepair** [comment]
So net.IP (which stores the ip address as a series of bytes) shows:
net.IP{0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x1} 
the code i use to write/serialize it to the connect token buffer:
```Go
for i := 0; i < len(parsed); i += 2 {
    var n uint16
    n = binary.BigEndian.Uint16([]byte(parsed[i : i+2]))
        buffer.WriteUint16(n)
}
```
shows: []byte{0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x1, 0x0}
if i change the binary.BigEndian.Uint16 to binary.BigEndian.Uint16(...) i get:
[]byte{0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x1}
(Note that buffer.WriteUint16(n) does the following:
```Go
b.Buf[b.Pos] = byte(n)
b.Pos++
b.Buf[b.Pos] = byte(n >> 8)
b.Pos++
```

**Comment by wirepair** [comment]
So giving this some more thought, I think the reason is completely on my side, since net.IP already stores it in big endian, converting those bytes again to big endian again actually flips it back to being little endian. We can probably close this.

**Comment by gafferongames** [comment]
Makes sense. There are similar endian issues in the C API for parsing IP addresses too, it's tricky.
