### ISSUE TITLE
Native C# Implementation

### ISSUE THREAD

**Issue by SProst** [networkprotocol/netcode.io#19]
Native implementation of netcode.io in C#. Question, what language specification can we target? I think there are enough language features to warrant supporting C#7 at this point. Were you planning on supporting netcore, netstandard, or the full dotnetframework (or target against all of them). NET core 1.1, Net Standard 1.5 (eventually 2?) and NET 462.

**Comment by gafferongames** [comment]
I think the best target ideally would be such that people coding Unity 5.6 (latest release) can use netcode.io natively from inside Unity.

**Comment by gafferongames** [comment]
My understanding is that Unity is using Mono 4.4

**Comment by gafferongames** [comment]
Some more information here: http://www.mono-project.com/docs/about-mono/releases/4.4.0/

**Comment by SProst** [comment]
Thanks! That was precisely the direction I was looking for.

**Comment by SProst** [comment]
https://forum.unity3d.com/threads/net-standard.451314/ Looks like Unity is looking to support netstandard 2 (whenever that is finally released)

**Comment by gafferongames** [comment]
Seems like for the current generation of Unity: "you'll need to stick to .NET 3.5 to be safe."

**Comment by gafferongames** [comment]
Maybe start with a basic implementation with .NET 3.5, and provide an upgraded version using more language features when as they become available in a widely released Unity version? 

From a game development point of view, Unity is the largest base of active C# users, so it would be ideal to support them.

**Comment by gafferongames** [comment]
And I should apologize, I'm not super up to date with all the intricacies of C# versions and .NET. My limited exposure to the language is using Unity 5.6 and it definitely seems to be an older version of the language.

**Comment by gafferongames** [comment]
The biggest question I think is, is there a libsodium version for C# that is native, or support for the chachapoly natively in C#? Ideally, a pure C# version would be available, without dependencies on a DLL, but if that DLL is necessary, it's not the end of the world.

**Comment by gafferongames** [comment]
This may be helpful: https://github.com/adamcaudill/libsodium-net

**Comment by gafferongames** [comment]
Oh and also, there is a C# wrapper for the API, which might also be useful as a starting point: https://github.com/RedpointGames/netcode.io

**Comment by gafferongames** [comment]
ps. There is no need for anybody to feel constrained to the C API, feel free to adapt it to the best approach you see for the C# language.

**Comment by SProst** [comment]
Looks like the libsodium-net library is a net40 compliant wrapper which means we'll need to rely on Mono's support of 4.0 csproj projects. I don't see why that should be an issue as far as supporting Unity is concerned, although I understand the need to prefer a native implementation of libsodium in C#.

The dot net framework has undergone a significant change over the course of the last 12-18 months, starting with dnx and corefx, specifically netstandard and netcore for cross platform support. Prior to that you had to rely on platform specific PCLs which got the job done but were not unified. 

Thanks for the links to the wrapper, I'll use that as a reference moving forward. I agree - when implementing a library in a native language it's important to focus on idiomatic programming so that it doesn't look like C code ported to C#. This is especially important for consumers of the API / library, who will expect idioms similar to other .NET libraries that they have consumed in the past.

**Comment by gafferongames** [comment]
Sounds like this is resolved. If you have further questions, DM me on twitter and we can discuss further. cheers

**Comment by rlabrecque** [comment]
Unity 2017 now supports C#6 & .NET 4.6

What's the current status on this? I have some free time and I was thinking of adopting this as a side project.

**Comment by gafferongames** [comment]
The current status is that it's available for you to work on!

**Comment by benaadams** [comment]
Can use any version of C# for implementation (e.g. C#7) just need to target the right version of [.NET Standard](https://github.com/dotnet/standard/blob/master/docs/versions.md) rather than the confusing mix of PCL versions,

Currently I think to get Unity, Xamarin.iOS/Mac/Android and UWP (Xbox, Win10) that would be a max of .NET Standard 1.4?

**Comment by gafferongames** [comment]
Hey guys, if you want to do it, please grab your code editor and your C# compiler and write some code. There is no need to discuss it to death. Code talks, BS walks.

**Comment by KillaMaaki** [comment]
I'm actually tentatively writing some code that I hope will turn into a fully managed C# implementation of Netcode.IO. At the very least I've got functioning code which can decrypt private connect tokens. It's not much, but it's a start :)
Of course it's nowhere near even ready for starting a repo yet, but ideally the goal is for it to be a *fully* managed implementation for maximum portability (so no wrappers or native DLLs anywhere - instead of using libsodium I'm currently using a modified version of the Bouncy Castle libs for crypto), as GC friendly as possible, and target .NET 3.5 so it can be used in Unity projects.

**Comment by gafferongames** [comment]
https://github.com/KillaMaaki/Unity-Netcode.IO

!!!
