### ISSUE TITLE
Linked paper is a 404

### ISSUE THREAD

**Issue by derekargueta** [networkprotocol/netcode.io#2]
URL to the whitepaper in the README doesn't work.

![image](https://cloud.githubusercontent.com/assets/5253821/23351479/a4930c44-fc7e-11e6-9334-3f949dabf198.png)

**Comment by derekargueta** [comment]
I believe I found it here: http://new.gafferongames.com/post/why_cant_i_send_udp_packets_from_a_browser/

**Comment by gafferongames** [comment]
Fixed. thank you!
