### ISSUE TITLE
Upgrade to IETF version of chacha20poly1305 with 96bit nonce

### ISSUE THREAD

**Issue by wirepair** [networkprotocol/netcode.io#33]
Here's a diff to support ietf 96bit nonces, I would have done a PR but my branch is not stable yet and i didn't want to push a bunch of changes that would make it hard to track. It's a very basic diff, just increasing nonce sizes, padding the first 4bytes with a uint32(0) and changing the libsodium calls to use the ietf version. I ran all tests and they passed, ran the server and had my go client communicate with no problems.

For your review:
[netcode_ietf.diff.txt](https://github.com/networkprotocol/netcode.io/files/957569/netcode_ietf.diff.txt)

**Comment by gafferongames** [comment]
On it

**Comment by gafferongames** [comment]
Merged.
