### ISSUE TITLE
Sequence number encoding

### ISSUE THREAD

**Issue by superfuchs** [networkprotocol/netcode.io#39]
There's an error in the example for sequence number encoding in the spec.
`0x000003E8` requires only 2 bytes: `0xE8` and `0x03`.

Also, I'm a bit confused about the byte order of sequence numbers in the packet. The pseudo code indicates that it should be little-endian, is this correct?

**Comment by gafferongames** [comment]
Thanks! I'm travelling right now but I will look at this very soon

**Comment by gafferongames** [comment]
Fixed.
