### ISSUE TITLE
Elixir implementation

### ISSUE THREAD

**Issue by fire** [networkprotocol/netcode.io#40]
Haven't started work but here's a placeholder. 

Elixir is a dynamic, functional language designed for building scalable and maintainable applications. Elixir leverages the Erlang VM

I wish to make this a library for elixir too.

**Comment by fire** [comment]
https://hex.pm/packages/libsodium dependent library

**Comment by gafferongames** [comment]
OK sounds good!

**Comment by fire** [comment]
Do you have a series of tests? Looking for something that goes from the simple features to the more complicated ones.

**Comment by gafferongames** [comment]
Yes, the tests are at the bottom of netcode.c:

https://github.com/networkprotocol/netcode.io/blob/master/c/netcode.c

**Comment by fire** [comment]
@gafferongames Can you generate some samples of the connect token / connect token data packets? I'm currently trying to write a decoder for it.

https://github.com/fire/netcode/blob/master/lib/netcode/ConnectTokenData.ex
https://github.com/fire/netcode/blob/master/lib/netcode/ConnectToken.ex

**Comment by gafferongames** [comment]
You should be able to do so pretty easily with the C reference implementation:

> int netcode_generate_connect_token( int num_server_addresses, 
                                    NETCODE_CONST char ** server_addresses, 
                                    int expire_seconds, 
                                    uint64_t client_id, 
                                    uint64_t protocol_id, 
                                    uint64_t sequence, 
                                    NETCODE_CONST uint8_t * private_key, 
                                    uint8_t * connect_token );

**Comment by fire** [comment]
Well my approach is to use an elixir implementation of the code, but it's possible to write a shared library that is loaded into elixir.

I'll take a look.

**Comment by gafferongames** [comment]
Yes I just mean as a transition, obviously you end up with 100% Elixir in the end.
