### ISSUE TITLE
Clang and ISO C++11 compatibility

### ISSUE THREAD

**Issue by pperon** [networkprotocol/netcode.io#41]
Hello! First and foremost, thanks for your work on this. I've been trying to improve my C/C++ and network programming skills and netcode.io makes for an excellent project to learn from. That being said, I've been using clang++4.0 [`-std=c++11 -Werror`] on Linux as my primary dev environment and when I include netcode.h and attempt to initialize it, a series of errors like the following emerge:

`ISO C++11 does not allow conversion from string literal to 'char *' `

My [fix](https://github.com/pperon/netcode.io/commit/0028608856e40ccd4fee73900d350c0325e6a2da) was just to change 'char *' to 'const char *' on arguments and return values (among others) that were causing problems. Does this feel like an appropriate way to handle this issue?

Thanks again. netcode.io rocks.

**Comment by gafferongames** [comment]
I'm not 100% sure I can do this, since old style C won't allow const. Is there some #ifdef way we can use the const char* only if it is C++ instead?

**Comment by pperon** [comment]
Ah, OK. I wasn't aware const was a problem with old style C. I'll look into another solution and get back to you!

**Comment by gafferongames** [comment]
I think if we can find an #ifdef that tests if C89 or greater, or C++, then we can use const, then this will solve both problems. const was introduced to C in C89.

**Comment by gafferongames** [comment]
To be clear, I'm very happy to solve this, we just have to work out how to maintain compatibility with old style C as well.

**Comment by pperon** [comment]
Hey! Sorry, I've been wrapped up in other things and haven't had a chance to work on this. Two questions for you if you have a moment. First, in removing my "const"s I saw that a few others remained. Specifically the netcode assert and printf functions. Should these be removed as well? Lastly, do you have a recommendation for validating that the fix complies with pre-c89 specifications? I didn't see any obvious compiler flags but admit this is new territory for me. Thanks.

**Comment by gafferongames** [comment]
Yes, there are similar C++11 complaints re. const char* literals that I worked around, that should be fixed in the same way. I can dig in and see if there is some way to detect this, otherwise it could be "NETCODE_HAS_CONST 1" up to the user or something like this. cheers

**Comment by gafferongames** [comment]
Should be resolved in https://github.com/networkprotocol/netcode.io/commit/e6dbc8bee3e0642e6e74b188a3abff4b9a56b982

**Comment by pperon** [comment]
You beat me to it! *hat tip*
