### ISSUE TITLE
Spec/implementation mismatch: Connect token address type byte?

### ISSUE THREAD

**Issue by KillaMaaki** [networkprotocol/netcode.io#44]
While working on my implementation based on the spec at https://github.com/networkprotocol/netcode.io/blob/master/STANDARD.md, I hit a bit of a snag: while the spec says that in the private connect token, for each server address, a byte identifies the address type and is either 0 or 1, I was getting a 1 byte despite the buffer clearly containing an IPv4 address (first four bytes were 127, 0, 0, 1, and the next two bytes together formed the port I had bound my server to). I'm not generating my own token yet, I'm using the server example that comes with the Netcode.IO browser project over at the Redpoint Games github, and that one just calls into native code, so this isn't an issue with an invalid connect token as far as I can tell.

So after digging through the C code I noticed that it defined the following:

```c
#define NETCODE_ADDRESS_NONE 0
#define NETCODE_ADDRESS_IPV4 1
#define NETCODE_ADDRESS_IPV6 2
```

And, later, it just writes the same values into the buffer. Which would make sense, as it means a value of 1 actually means IPv4, not IPv6, as hinted at by the 127, 0, 0, 1 bytes. If this is true and I haven't missed something (which is entirely possible, it's late and I'm tired), I'd suggest the docs be modified to indicate that valid values are actually 1 and 2, not 0 and 1.

**Comment by gafferongames** [comment]
Very nice catch. Thank you! I will update the spec to match the reference code. The value of 0 means "no address".
