### ISSUE TITLE
Go server implementation usage

### ISSUE THREAD

**Issue by toqueteos** [networkprotocol/netcode.io#45]
I'm doing some tests with netcode, specifically with Go's server implementation and I'm struggling a little bit.

The C implementation exposes a very nice API to send/receive packets to a single client.

The Go implementation only exposes `Server.SendPayloads` ([source][1]) which sends something to all connected clients.
Am I missing something?

/cc @wirepair

[1]: https://github.com/networkprotocol/netcode.io/blob/8f8ff407bba7a930ffe681e286e95a396a38165c/go/netcode/server.go#L115

**Comment by toqueteos** [comment]
I'm checking out `Server.OnPacketData` ([source][1]) but by the name, and looks, it seems it just for reading client packets from the server.

[1]: https://github.com/networkprotocol/netcode.io/blob/8f8ff407bba7a930ffe681e286e95a396a38165c/go/netcode/server.go#L153

**Comment by wirepair** [comment]
Hu, not sure how I missed that when I was translating the C code. Should be easy to expose the clientManager clients and allow to send via client index value. I'll work on this tonight, thanks for taking a look at it!

**Comment by wirepair** [comment]
OK, just got a quick implementation of it in (need to write tests which may take some time, maybe by tomorrow). I also realized there was no way to disconnect clients via the server. Do these two signatures look good to you?
```Go
// Sends the payload to the client specified by their clientId.
func (s *Server) SendPayloadToClient(clientId uint64, payloadData []byte, serverTime float64) error {
	clientIndex, err := s.getClientIndexByClientId(clientId)
	if err != nil {
		return err
	}

	s.clientManager.sendPayloadToInstance(clientIndex, payloadData, serverTime)
	return nil
}

// Disconnects a single client via the specified clientId
func (s *Server) DisconnectClient(clientId uint64, sendDisconnect bool, serverTime float64) error {
	clientIndex, err := s.getClientIndexByClientId(clientId)
	if err != nil {
		return err
	}

	s.clientManager.DisconnectClient(clientIndex, sendDisconnect, serverTime)
	return nil
}
```

**Comment by toqueteos** [comment]
Yes, they do make a lot of sense!
Thanks for responding so quickly 👍

**Comment by wirepair** [comment]
np, let me know if you want any thing else exposed, i tried to hide the details of managing clients as much as possible, i guess a little too much :/.

**Comment by toqueteos** [comment]
That should be enough for now, I'll continue testing/reviewing code and if something weird pops out I'll open a new issue.

**Comment by gafferongames** [comment]
My preference would be to send and receive data to clients based on their client index, not their client id. Client id is a weird 64bit guid, while client index is [0,maxClients-1]. This would match how the C implementation does it.

Of course, you add a method to get a client index for a client id, eg. int FindClient( uint64_t clientId ) or something like that so you can lookup by client id too.

cheers

- Glenn

**Comment by gafferongames** [comment]
For example, you can see the C implementation does it in a particular way, and always looks up clients by client index. It would be nice if you could do that too for consistency.

**Comment by wirepair** [comment]
So technically that *is* what I'm going to be doing in server.go:
```Go
func (s *Server) getClientIndexByClientId(clientId uint64) (int, error) {
	if !s.running {
		return -1, errors.New("server is not running")
	}

	clientIndex := s.clientManager.FindClientIndexById(clientId)
	if clientIndex == -1 {
		return -1, errors.New("unknown client id " + string(clientId))
	}
	return clientIndex, nil
}
```
Where clientManager will return the clientIndex of the client in the array. I am assuming implementers will have copies of the clientId but not the index, is that correct?

**Comment by gafferongames** [comment]
Yeah that looks great. Then everything else works from clientIndex.

**Comment by gafferongames** [comment]
ps. I updated the golang code to 1.01 version of the spec, take a look at it. It's a minor change (look at last few revs on STANDARD.md). Was necessary to get the timeout value passed properly from connect token through to server on client connect. This lets clients specify -1 timeout values, which should disable the timeout (it's good for debugging).

Could you check your implementation on your side and updated it to handle negative timeout values in the connect token (per-client), to mean "disable timeout for this client". Also, per-client timeouts in the connect token private data should be respected on the client, and in the encryption mapping.

Let me know if this doesn't make sense. It's coming from a particular user of the library and their desire to set per-client timeouts. I intended to add this in 1.00, but kinda screwed it up and forgot to put the timeout in the private connect token data... dur

**Comment by wirepair** [comment]
OK yeah cool I kept that pretty much inline with the C code, i just put all client management in it's own component instead of having it directly in the server code, other than that it should be the same as the C implementation. (Minus the fact that I forgot to expose the above functionality!)

**Comment by gafferongames** [comment]
Uh. Yeah I'm not 100% sure my changes are correct btw. I tried to update the version to 1.01, but when I am calling the golang code from yojimbo to generate connect token for yojimbo, it's complaining that the version is incorrect. Is there somewhere else in the golang code that writes out the version info manually for the connect token?

**Comment by wirepair** [comment]
Hmm, nope I only have one constant https://github.com/networkprotocol/netcode.io/blob/7b2296858c8973d75f6b4abccc62ef4052f8d55c/go/netcode/packet.go#L22. Did you run the test cases after your change and they all passed?

**Comment by gafferongames** [comment]
I did change that, but it's still breaking in my matcher.go. How do I run the tests? There is no documentation or anything in README.md...

**Comment by wirepair** [comment]
ah, i'll add that too, just go test -v. Is your code something you could share? I can take a look at it when I update the other code.
So I have:
1. Expose sending packets per-client
2. Expose disconnecting clients
3. Add more information to readme (including testing)
4. Re-test compatability between c/go. I think I need to implement a cgo package so we can make sure further changes don't break.

**Comment by gafferongames** [comment]
My code is all in netcode.c, plus I have committed the golang code to the repo.

**Comment by wirepair** [comment]
Ahh yeah that'll do it :). go get -u github.com/networkprotocol/netcode.io/go/netcode for updating.

**Comment by wirepair** [comment]
or just go get -u in the netcode directory. Did that fix your issue?

**Comment by gafferongames** [comment]
It was a docker issue. Docker was not re-running the command, because it didn't realize there was an updated external dependency. Seems to be working now. I checked in some additional fixes so the connect token timeout value isn't zero. all tests pass. Something broken on the yojimbo side now that i'm digging into...
