### ISSUE TITLE
Go implementation Buffer.GetBytes panics

### ISSUE THREAD

**Issue by toqueteos** [networkprotocol/netcode.io#46]
I'm digging into Go's codebase and found a bug in `Buffer.GetBytes`.

Here's a playpen to see it in action:
https://play.golang.org/p/3-1uLvXD83

I'll send a PR with a fix for this and the corresponding test.

**Comment by wirepair** [comment]
woops yeah, probably want to check the Pos + length.. my bad, thanks for finding this!
