### ISSUE TITLE
Question: Does the webserver need to save the IVs?

### ISSUE THREAD

**Issue by fire** [networkprotocol/netcode.io#51]
According to the crypto spec, the ivs cannot be repeated. There's a variant that allows random ivs, but it's a different algo. 

What is the recommended algorithm to avoid this?

**Comment by fire** [comment]
```Encryption of the challenge token data is performed with the libsodium AEAD primitive crypto_aead_chacha20poly1305_ietf_encrypt with no associated data, a random key generated when the dedicated server starts, and a sequence number that starts at zero and increases with each challenge token generated. The sequence number is extended by padding high bits with zero to create a 96 bit nonce.```

If the server restarts, do we generate a new key and start from 0? Keeping the old key and restarting from 0 is a bad idea.

**Comment by fire** [comment]
```The private portion is encrypted and signed with a private key shared between the web backend and dedicated server instances.```

This sharing means we reuse the private key. How do we make sure that iv incrementing is synchronized.

**Comment by gafferongames** [comment]
> This sharing means we reuse the private key. How do we make sure that iv incrementing is synchronized.

The private key is shared but the nonce is a sequence number that increments with each connect token generated by the matcher. If the matcher shuts down, it should for best practice, not restart the nonce at zero, but continue with the last sequence # generated + 1.

cheers
