### ISSUE TITLE
Quick UDP Internet Connection

### ISSUE THREAD

**Issue by bogdanbiv** [networkprotocol/netcode.io#53]
FYI There is one initiative for bringing UDP (and much more) to the browser QUIC
(Quick UDP Internet Connection).

Here is its home page; https://quicwg.github.io/
Found it via https://www.simpleservers.co.uk/2017/07/litespeed-web-server-supports-quic

**Comment by gafferongames** [comment]
QUIC is known, but is not quite suitable for the sort of UDP that netcode.io provides. -- cheers

**Comment by getkey** [comment]
Things have changed since 2017, now QUIC is starting to look interesting for that use-case https://wicg.github.io/web-transport/ :slightly_smiling_face:
