### ISSUE TITLE
Expose client IPs/ports in API

### ISSUE THREAD

**Issue by daseyb** [networkprotocol/netcode.io#54]
I could be missing something, but right now there doesn't seem to be a way to get the address/port of a connected client from a server instance.

Are there any concerns about adding ```netcode_address_t``` to the API and adding a method like ```netcode_address_t netcode_server_client_address(int client_index)``` that returns the appropriate entry from ```netcode_server_t::client_address```?

**Comment by gafferongames** [comment]
Yes. I don't want to expose the netcode_address_t as a public interface. The idea behind this is to keep  the interface simple, eg. only pass addresses around as strings.

So if you want to add a function that returns the client address as a string, I'm OK with that, but not as a netcode_address_t

cheers

**Comment by daseyb** [comment]
Ah, that makes sense! I'm fairly new to network programming and wasn't sure if there was a security issue to worry about. :)

I had actually added ```void netcode_server_client_address(struct netcode_server_t * server, int client_index, char* client_address);``` in my fork. Since it's so straightforward I'm not sure if it's worth submitting a pull request, but I can do that if you want.

Cheers, Dario
