### ISSUE TITLE
Both IPv6 and IPv4 IP addresses in a single connect token?

### ISSUE THREAD

**Issue by MattFoley** [networkprotocol/netcode.io#57]
After working through some mobile networking trouble, we found that some cell providers work better with IPv6 while some work better with IPv4. 

In testing, we found that IPv6 connect tokens only work properly when the Yojimbo client is initialized with an IPv6 address to bind to.

```
// Will not work with an IPv6 address as the only server address in the connect token.
Client* client = new Client(GetDefaultAllocator(), Address("0.0.0.0"), config, adapter, time);
vs:
// Works with an IPv6 address in the connect token.
Client* client = new Client(GetDefaultAllocator(), Address("0:0:0:0:0:0:0:0"), config, adapter, time);
```

We then tracked this down to `netcode_socket_create` in netcode.c, the address the client binds to must match the protocol (IPv4 vs IPv6) of the address container in the connect token. While the address that's used for `sendto` is being handled as IPv6 correctly, it fails if the socket wasn't created for an IPv6 client.

At the moment, we're unsure whether this is a bug, or by design. Should netcode/yojimbo be able to handle connect tokens with both IPv4 and IPv6? Is it possible we're doing something wrong here? Is this a bug with one of these two libraries?

If this isn't a supported feature, would you have any suggestions for this? If it is, and seems to be working as expected, is it possible we're not binding the client address correctly?

**Comment by armandgray** [comment]
Working through the problem we have found a workaround. For testing purposes, we have been able to allow both ipv6 & ipv4 addresses to pass through the created socket by setting the client's address to ipv6 (eg `Address("0:0:0:0:0:0:0:0")`) & removing replacing the assignment of the client address in `netcode_socket_create` with `socket_address.sin6_addr = in6addr_any;`. Changes:

```
...
    // Don't force ipv6 only.  Allow both type of connections.

    if ( address->type == NETCODE_ADDRESS_IPV6 )
    {
        int yes = 0;
        if ( setsockopt( s->handle, IPPROTO_IPV6, IPV6_V6ONLY, (char*)&yes, sizeof(yes) ) != 0 )
        {
            printf( "error: failed to allow other protocols over ipv6\n" );
            netcode_socket_destroy( s );
            return NETCODE_SOCKET_ERROR_SOCKOPT_IPV6_ONLY_FAILED;
        }
    }
...
    if ( address->type == NETCODE_ADDRESS_IPV6 )
    {
        struct sockaddr_in6 socket_address;
        memset( &socket_address, 0, sizeof( struct sockaddr_in6 ) );
        socket_address.sin6_family = AF_INET6;
        socket_address.sin6_addr = in6addr_any;
        socket_address.sin6_port = htons( address->port );

        if ( bind( s->handle, (struct sockaddr*) &socket_address, sizeof( socket_address ) ) < 0 )
        {
            printf( "error: failed to bind socket (ipv6)\n" );
            netcode_socket_destroy( s );
            return NETCODE_SOCKET_ERROR_BIND_IPV6_FAILED;
        }
    }
...
```

The workaround above obviously has security issues and we were also forced to temporarily remove the whitelist check. On the other hand, the result was that both client and server were able to send & receive both ipv4 & ipv6 data over the same socket. 

One issue did arise when the client with an ipv6 address connected to the server through an ipv4 address. In this case, the `netcode_address_equal` function would reject the `NETCODE_CONNECTION_CHALLENGE_PACKET` coming `from` and ipv6 address while the `&client->server_address` was an ipv4 address. The snippet below adjusting the type check in `netcode_address_equal` allowed us to work around this problem as well:

```
    if ( a->type != b->type )
    {
        char ipv6[NETCODE_MAX_ADDRESS_STRING_LENGTH];
        char ipv4[NETCODE_MAX_ADDRESS_STRING_LENGTH];

        if ( a->type == NETCODE_ADDRESS_IPV6 && b->type == NETCODE_ADDRESS_IPV4 )
        {
            netcode_address_to_string( a, ipv6 );
            netcode_address_to_string( b, ipv4 );
        }
        else if ( a->type == NETCODE_ADDRESS_IPV4 && b->type == NETCODE_ADDRESS_IPV6 )
        {
            netcode_address_to_string( a, ipv4 );
            netcode_address_to_string( b, ipv6 );
        }
        else
        {
            return 0;
        }

        size_t size = (size_t) (strlen(ipv4) - (floor( log10( b->port ) ) + 1) + 1);
        return memcmp( ipv4, ipv6 + 8, size );
    }
```

The final result is that a single client can reach the `CONNECTED` state over ipv4 or ipv6. We are still looking for viable, secure solutions. The questions mentioned in the previous comment still stand: Is a netcode client intended to be able to connect to both ipv4 & ipv6? Would you have any suggestions for this?

**Comment by gafferongames** [comment]
Can confirm this workaround solution is not secure. The real solution I think is to add first class support for dual ipv4 and ipv6 sockets inside the netcode_socket_t implementation. eg. create two sockets, one for ipv4 and one for ipv6. This way it would pass up to yojimbo, perhaps with some changed signature, eg. you have to pass the ipv4 and the ipv6 bind addresses.

I feel this would be a lot of work, but it definitely seems the right approach.

Seems best to approach this by making changes and proving it out in netcode.io first, and then porting up to yojimbo.

Thoughts?

**Comment by MattFoley** [comment]
That makes sense, it's something that we'll hopefully have time to work on done the road. Thanks for the advice.

Just a heads up, it turns out that while the hybrid IPv4/IPv6 socket works on Android and Linux, it is not supported on iOS. Instead we've implemented a solution higher up and mostly outside of Yojimbo/Netcode to manage IPv4 vs IPv6.

**Comment by armandgray** [comment]
The final addition we had to implement for the above was to expose the client address and change the address from ipv4 to ipv6 (and back), while overwriting server_addresses that do not match the ip format in `netcode_read_connect_token`. 

If we add an appropriate whitelist back in would this approach be secure?

**Comment by gafferongames** [comment]
I think the ultimate correct approach here, is that netcode.io servers should simultaneously support connection via IPv6 or IPv4 at the user's discretion.

I think such a change is a perfect feature addition, and it definitely should be done.

Calling out to everybody out there, what is the best way for us to do this, should we have multiple sockets per-netcode.io server, eg. one for ipv4 an one for ipv6, or something else?

cheers

- Glenn

**Comment by gafferongames** [comment]
ps. I'm very interested in adding this, but right now I'm also very busy with my new startup. If anybody wants to have a crack at this, I'm happy to review the changes.

**Comment by armandgray** [comment]
Sounds good. I've actually been working on getting a solution for this ready. I'd like to get some thorough testing completed on the changes before push anything up. I should have a PR up this coming week.

**Comment by gafferongames** [comment]
I have a suggestion, for backwards compatibility, could you implement it without changing the signature.

For example, when passing in addresses, use the form:

"[ipv4]|[ipv6]"

For example:

"127.0.0.1|::1"

This would retain compatibility with yojimbo, which uses netcode.io, and make the functionality you add work for people who use that library too.

Of course, you should still support single addresses, but add the "x|y" format to support up to two sockets per-client/server.

cheers

- Glenn

**Comment by gafferongames** [comment]
And of course, please extend the tests to have a test case with your addition!

**Comment by armandgray** [comment]
Alright. I put [this](https://github.com/networkprotocol/netcode.io/pull/60) PR up. It's got the support for passing 2 addresses & creating 2 sockets when creating the server and the client. 

I added a decent description covering the changes, but you might find the test cases to be a bit much based on the testing that was previously incorporated. 

Obviously the Travis build failed. I already tried to get that passing a few times, but the tests aren't failing for me locally. Maybe you could point me in the right direction. Otherwise, I'll take a look tomorrow. 

As far as implementation goes, the changes are backwards compatible as I made sure not to change the signatures for `netcode_client_create` & `netcode_server_create`. I've allowed the ipv4/ ipv6 addresses to be passed in in any order (or in theory 2 ipv4/6's). Let me know if you require any changes.

**Comment by gafferongames** [comment]
Try running the tests under linux. What OS are you developing on?

**Comment by gafferongames** [comment]
ps. Good call on the any order. Excellent

**Comment by gafferongames** [comment]
ps. If you don't have easy access to linux (eg. developing under Mac, Windows), try running a plain docker ubuntu instance. Really easy to test under there. That's how I do it.

**Comment by armandgray** [comment]
Tests are passing. For some reason it wasn't able to bind to the ipv6 loopback in the `test_client_create` suite. Maybe you can enlighten me as to why. 

Hopefully you could leave any comments or approval you see fit on the PR and we can move forward from there.

**Comment by gafferongames** [comment]
I've noticed IPv6 weirdness in Travis too. I don't think it's you. I think it's however they've setup the networking for those VMs. Nice find. Accepting pull request now. Nice work!
