### ISSUE TITLE
NETCODE_MAX_CLIENTS preprocessor directive

### ISSUE THREAD

**Issue by nxrighthere** [networkprotocol/netcode.io#58]
@gafferongames Hi Glenn! I'm currently working on an [app](https://github.com/nxrighthere/BenchmarkNet) for testing the reliable UDP networking solutions. I successfully integrated netcode.io into it (using C# bindings and a reliability layer on top of it) and it works absolutely great! But unfortunately, it's not allowed to have more than 256 simultaneous connections. So my question is - if I want to bypass this limitation, it's fine to change the NETCODE_MAX_CLIENTS preprocessor directive or it's a bad idea?

**Comment by gafferongames** [comment]
Yes, it's OK to increase! I have successfully increased up to around 2048 or so, and it works fine.

Of course, you may start to hit bottlenecks (this is not software designed for MMOs...), but it does work pretty well!

cheers

- Glenn
