### ISSUE TITLE
Disconnect callback function is called before server->num_connected_clients is decremented

### ISSUE THREAD

**Issue by maxw** [networkprotocol/netcode.io#59]
I'd like to store the state of my game server once all players have left. However, netcode calls `connect_disconnect_callback_function()` before `server->num_connected_clients--;`, which means that the number of connect clients is 1 when the last disconnect callback fires.

I thought about moving the callback to the bottom, but it seems like a good amount of metadata about the connection is reset that may be useful to those subscribing to the callback (yojimbo for example).

Would it make sense to move the `    server->num_connected_clients--;` line to before `connect_disconnect_callback_function()` in `netcode_server_disconnect_client_internal`?

Max

**Comment by gafferongames** [comment]
I don't mind if you make this change and submit a pull request, provided that all tests pass.

cheers

**Comment by maxw** [comment]
Are you ok with me renaming these methods to `OnServerDidConnectClient(int clientIndex)` / `OnServerWillDisconnectClient(int clientIndex)`? That's how I name methods when I follow this same pattern in my own libraries.

**Comment by gafferongames** [comment]
No thanks! Please leave them as they are. We don't want to break the interface for other users of the library.
