### ISSUE TITLE
usage guide?

### ISSUE THREAD

**Issue by mreinstein** [networkprotocol/netcode.io#61]
All of the documentation referenced in the readme are geared torwards protocol implementors and people looking for details on how it works internally.

Are there any documentation/guides on how to use the netcode.io interface?

**Comment by gafferongames** [comment]
Good point, there isn't yet, but there should be.

cheers

**Comment by mreinstein** [comment]
@gafferongames I'm happy to help with this if that would be appreciated. What's the minimal/best place to see how to set up an end-to-end demo?

**Comment by gafferongames** [comment]
Thanks. This would be really helpful. So far the best documentation is kindof in the unit tests, and the soak test. Also, looking at netcode.h, the header there is actually only I think 20 functions?

**Comment by gafferongames** [comment]
Actually, to be fair, the best examples are in client.c and server.c

**Comment by gafferongames** [comment]
or maybe even client_server.c for sort of a top-down view of both sides

**Comment by mreinstein** [comment]
hmm, alright. I guess probably what makes sense is for me to look at the those 3 files and try to set up an integration from scratch. Where's the best place to pester people with questions that come up as I go through this? this github issue or slack/gitter?

**Comment by gafferongames** [comment]
Yeah, you could just pester me here, I don't mind.

**Comment by mreinstein** [comment]
I've looked over `client.c`, `server.c`, and `client_server.c`. I think I have a reasonable idea of how to set this up. 3 questions that come to mind right now:

* In the README, the 1st listed feature is "connection oriented". But in the netcode 1.0.1 standard, it seems that the whole thing is implemented over UDP, which is connectionless. Am I just getting tripped up on nomenclature here?

* Is netcode's goal solely handling the matchmaking and encryption aspects of the transport? I'm assuming that whatever game/simulation one builds would likely us yojimbo on top of this for all the higher level sending capabilities?

* for the browser plugin, why expose netcode's interface, rather than the higher level abstractions that something like yojimbo provides? It seems like the very next thing someone who gets netcode.io working in their web game working would want to do would be to have access to message channels, etc.

**Comment by mreinstein** [comment]
@gafferongames an initial stab at a usage guide:

https://gist.github.com/mreinstein/0284fbab6955c246d54224db5f402a24

I took the approach of using c/pseudocode and commenting on the critical code blocks that set up server and client instances.

I know this is super rough but hopefully it's a starting point. Would love some feedback/ideas on how to refine this.

One area that would be great is explaining how to handle multiple servers which I think I saw elsewhere but wasn't sure how to set up.

**Comment by mreinstein** [comment]
I'd like to reiterate that the above is just a 1st pass. If this looks promising I'm happy to collect (hopefully constructive) feedback and make the 2nd pass on this.

**Comment by mreinstein** [comment]
no worries, I just wanted to ensure any concerned parties this is not anywhere near the final quality/end result. I'm a big believer in rapid iteration and sharing things early to get feedback. When anyone gets a chance to take a look and give notes I'll make another improvement round. :)

**Comment by mreinstein** [comment]
I haven't forgotten about this, still planning to do another update today or tomorrow after I un-bury myself from current work. :)

**Comment by amit1072** [comment]
> @gafferongames an initial stab at a usage guide:
> 
> https://gist.github.com/mreinstein/0284fbab6955c246d54224db5f402a24
> 
> I took the approach of using c/pseudocode and commenting on the critical code blocks that set up server and client instances.
> 
> I know this is super rough but hopefully it's a starting point. Would love some feedback/ideas on how to refine this.
> 
> One area that would be great is explaining how to handle multiple servers which I think I saw elsewhere but wasn't sure how to set up.

Hi mreinstein, I know its been a while, the github url didn't work, is this removed?

**Comment by mreinstein** [comment]
It has indeed been a while. Lost to the ages I'm afraid. :)
