### ISSUE TITLE
does netcode.io handle crc32 checking?

### ISSUE THREAD

**Issue by mreinstein** [networkprotocol/netcode.io#63]
I noticed that netcode.io *does* have a protocol id, wondering if it also does crc based integrity checking, or is this expected to be built at a higher level in the application?

**Comment by gafferongames** [comment]
It does even better!

netcode.io uses a cryptographically secure hash, which incorporates the protocol id and the packet contents.

It also securely encrypts the packet contents so they can’t be read.

Finally, it has replay protection so an attacker can’t record a packet and attempt to replay it to break your protocol.

Cheers

**Comment by mreinstein** [comment]
very nice, thanks 👍
