### ISSUE TITLE
Add compatibility with MinGW and cross compilation

### ISSUE THREAD

**Issue by Crunkle** [networkprotocol/netcode.io#65]
We were looking into using this library but found that it has no support for cross compilers. There are too many differences between MinGW GCC and MSVC for it to compile.

Upon inspection, it looks like `inet_pton` causes issues as, for the symbol to become declared, it requires Windows Vista macros to be set. Some of the old C99 compatibility macros from `inttypes.h` cause issues as well under MinGW builds.

**Comment by gafferongames** [comment]
Happy to accept a pull request to fix this if you have it. cheers
