### ISSUE TITLE
Forked rust implementation to support latest netcode.io

### ISSUE THREAD

**Issue by jaynus** [networkprotocol/netcode.io#68]
I have been working to port reliable.io to Rust to eventually implement a yojimbo clone in pure rust, which also included updating netcode.io. The current linked fork is rather old, and required some fixing for the latest version of netcode. 

My fork is available @ https://github.com/jaynus/netcode.io if you'd like to include another pure rust implementation. This is strictly a fork and fix of vvanders version, and I plan on expanding the implementation and supporting it - as he has dropped support for his (RE: https://github.com/vvanders/netcode.io/pull/1)

**Comment by gafferongames** [comment]
Brilliant, please create a pull request to the README.md for this project with a link to your stuff! You can also add yourself to the "These people are awesome" list if you like.

Thanks!
