### ISSUE TITLE
use of MAX_PACKET_BYTES vs MAX_PAYLOAD_BYTES in receive_packet functions

### ISSUE THREAD

**Issue by Kingsquee** [networkprotocol/netcode.io#76]
A question:
```
        *packet_bytes = packet->payload_bytes;
        netcode_assert( *packet_bytes >= 0 );
        netcode_assert( *packet_bytes <= NETCODE_MAX_PACKET_BYTES );
```
Since ```packet_bytes``` is actually ```packet->payload_bytes```, shouldn't the latter ```netcode_assert``` be comparing to ```NETCODE_MAX_PAYLOAD_BYTES```?

Found in the following locations:
https://github.com/networkprotocol/netcode.io/blob/master/netcode.c#L3359
https://github.com/networkprotocol/netcode.io/blob/master/netcode.c#L4858

**Comment by gafferongames** [comment]
Looks like you might be right. Do the tests pass if you make the change?

**Comment by gafferongames** [comment]
(in debug build obviously) :)
