### ISSUE TITLE
Spec/implementation mismatch: Random bytes written to user_data in netcode_generate_connect_token

### ISSUE THREAD

**Issue by stellarLuminant** [networkprotocol/netcode.io#78]
Based on the current spec, the user_data field in the private connect token should be user specified data (this means I assume the API should be able to receive user_data from an outside source). However, in netcode_generate_connect_token line 5081, a private connect token is generated with random bits filling the user_data field.

This seems like something that would be easy to fix with a user_data parameter in netcode_generate_connect_token. (I don't know C enough to be sure.)

**Comment by gafferongames** [comment]
Yes, the connect token generation is just for tests. You're welcome to update it if you wish.

**Comment by stellarLuminant** [comment]
Ahh, the RedpointGames netcode.io C# bindings uses this function as part of its API, so I got confused there. I don't know C too well, but I think I've studied the code well enough to make this very minor change (and run the tests).

**Comment by stellarLuminant** [comment]
Issue resolved in referenced pull request: #79
