### ISSUE TITLE
libsodium is /MT

### ISSUE THREAD

**Issue by TrianglesPCT** [networkprotocol/netcode.io#82]
There is no lib compiled as /MD, perhaps add it in addition to the /MT one?

Is this bloatware libsodium library really necessary, perhaps strip out the parts that are actually used?
It appears that netcode only calls 5 functions from this library--

Or add an option to disable this requirement..

**Comment by gafferongames** [comment]
I'm not hacking a crypto-primitive library that we depend on. That's a bad choice. libsodium is an open source library so you are free to compile it from source, yes?
