### ISSUE TITLE
netcode.io support x32?

### ISSUE THREAD

**Issue by MiLoserDie** [networkprotocol/netcode.io#87]
Hi, Glenn.
I recently found this excellent library by reading an article on your site.
I have a question regarding the compilation for x32 bit.
Can I compile a project as x32 bit .lib and use it stably? Or is it just x64 bit library? (Windows)

If so, what do I need to change in the code (netcode.io) so as not to run into problems.

Another question:
If you use x64 on the server and x32 on the client, are there any consequences?

**Comment by gafferongames** [comment]
Of course it supports 32bit. Just compile it that way :)
