### ISSUE TITLE
Settings #define's 

### ISSUE THREAD

**Issue by MiLoserDie** [networkprotocol/netcode.io#88]
Hi, Glenn
I'm a little confused in the macros, there are too many of them and they all have similar names.
I have a few questions, hope you can give me a detailed answer.

1) If the game client cannot send a packet of more than 6000 bytes in length, then what #define should I change? 
Me need change #define NETCODE_MAX_PACKET_SIZE in .c and .h file netcode?
My game client use 2 byte for proto ID and 5998 for data, example packet: [00 65][00 00 00 00]
where [00 65] - it's proto id, [00 00 00 00] - data

Why is #define NETCODE_SERVER_MAX_RECEIVE_PACKETS 64 * NETCODE_MAX_CLIENTS?
It's mean, 1 client can't send more 64 byte or how much packets he can accept?

It's correct? NETCODE_MAX_PACKET_BYTES = NETCODE_MAX_PAYLOAD_BYTES + 100 ?

My head is torn from the fact that macros are not commented out
Can you tell that each of these macros is doing, as well as how are the two of them interconnected?

Honestly, it would be easier if I contacted you directly so that you could help me set up netcode according to my project.

I hope you have a couple of minutes for me.

**Comment by gafferongames** [comment]
You should leave the #defines alone, and combine netcode.io with a solution like reliable.io that does MTU splits for you. It’s bad practice to send packets over the wire larger than a conservative MTU (as expressed in the defines).

Cheers

**Comment by MiLoserDie** [comment]
> You should leave the #defines alone, and combine netcode.io with a solution like reliable.io that does MTU splits for you. It’s bad practice to send packets over the wire larger than a conservative MTU (as expressed in the defines).
> 
> Cheers

Can you help us configure netcode.io + reliable.io for our specific project? We are willing to pay if required.
Can I contact you directly?

**Comment by gafferongames** [comment]
Sorry, I am not available for consulting. I’m the CEO of Network Next these days. 

To solve your problem, just use yojimbo. It has everything you need... do not use netcode.io, it is too low level for your needs.

**Comment by gafferongames** [comment]
Yojimbo incorporates netcode.io and reliable.io together into a form that does exactly what you need. Use that instead.

**Comment by MiLoserDie** [comment]
> Sorry, I am not available for consulting. I’m the CEO of Network Next these days.
> 
> To solve your problem, just use yojimbo. It has everything you need... do not use netcode.io, it is too low level for your needs.

Unfortunately, Yojimbo is not suitable for MMORPG, as it provides only "MaxClients = 64" players. Yojimbo is focused on MOBA or FPS games. In our case, we would like to support more than 1,000 players at the same time.

Can you advise which tool to use? Whether Yojimbo is suitable for us? My colleagues say that it is oriented for FPS games, as its transmission speed is too high for MMORPG, besides, it is focused on a limited number of connections.

**Comment by RandyGaul** [comment]
You can alter netcode to use some hash tables for lookups. You can also alter defined for send rate to be lowered. I personally did some back of the envelope math... and nothing is stopping netcode or yojimbo from scaling besides swapping some data structures here and there internally.

**Comment by MiLoserDie** [comment]
> You can alter netcode to use some hash tables for lookups. You can also alter defined for send rate to be lowered. I personally did some back of the envelope math... and nothing is stopping netcode or yojimbo from scaling besides swapping some data structures here and there internally.

What are you talking about? Either I did not understand you, or we are really talking about different things.

I need: reliable UDP protocol, but it worries me that in Yojimbo, the settings are focused on MOBA/FPS online games, where rooms are used and in each room there can be up to N players. In the MMORPG, this does not work.

**Comment by RandyGaul** [comment]
I’m saying you can use yojimbo but will probably have to edit the source of netcode and yojimbo to use different data structures internally.

**Comment by MiLoserDie** [comment]
In this case, how to configure Yojimbo so that it supports more than 1000 users and in addition, there are don't have channels in our game (rooms where <= 64 players gather)?

**Comment by RandyGaul** [comment]
Good question. I’m sure you can figure that out once you start working on your game.

**Comment by MiLoserDie** [comment]
> Good question. I’m sure you can figure that out once you start working on your game. Nobody will be able to answer this question except for the people working on your game.

I am already working on my game, but I didn’t think of anything better than launching streams, but in this case, the client IDs will be the same. The solution is also available, you can use the stream ID + client ID and create a hash that will not exactly match.

Have you been familiar with netcode, realible and yojimbo for a long time?
Maybe you can help us?
In addition, we need programmers, you may be interested in our project.

**Comment by RandyGaul** [comment]
I'm not interested, thanks for asking though! I suggest you look around on maybe gamedev.net or other forums if you need more engineering help.

**Comment by MiLoserDie** [comment]
I think that only Glenn can answer this question. He says that Yojimbo is what we need, but he did not say if Yojimbo is suitable for MMORPG games, where the number of customers in one world can exceed 1,000 players.

If this is possible, then I would like to hear from the author how to implement it.
Я имею в виду, как настроить Yojimbo для MMORPG

**Comment by gafferongames** [comment]
If you wish to make an MMO, you need to get some network engineering talent on to make that happen. If you don’t even have enough network engineering talent to adjust yojimbo/netcode.io to do basic things, perhaps you shouldn’t be making an MMO.

Peace out.
