### ISSUE TITLE
Switching between carrier and wifi when a connection has been established

### ISSUE THREAD

**Issue by supersolid-corentin** [networkprotocol/netcode.io#92]
Hi, we've got a mobile game with a custom implementation of netcode.io already live . (Almost) everything works fine except when switching between carrier network and wifi network as the server is not gonna recognize one or the other depending on which one the client uses to connect at the start.

Is there anything handling this in the protocol that I missed? If not, what would be the best way to handle that case so that the player can continue its game almost seamlessly?

**Comment by gafferongames** [comment]
Add your own custom user id via "user data" in your connect token, then implement your own joining protocol at the player level above net code.io, eg. map net code connections to higher level player join concept via your user id. That way you can transition from one net code.io connection to the newer one for the same player.

**Comment by Soulai** [comment]
Thanks for the answer :)
